sonar.projectName=ai-document-extraction-service
sonar.projectKey=ai-document-extraction-service
sonar.sources=app
sonar.tests=app/tests
sonar.python.file.suffixes=.py
sonar.inclusions=**/*.py
sonar.python.coverage.reportPaths=coverage.xml
#sonar.exclusions=**/venv/**,**/env/**,**/__pycache__/**,**/data/**,**/docker-images/**,**/services/__init__.py,**/app/__init__.py,**/utils/__init__.py
sonar.exclusions=**/venv/**,**/env/**,**/__pycache__/**,**/data/**,**/docker-images/**,
