sonar.projectName=ai-document-classification-service
sonar.projectKey=ai-document-classification-service
sonar.sources=app
#sonar.tests=tests
sonar.sourceEncoding=UTF-8
# File inclusions/exclusions (if needed)
sonar.inclusions=**/*.py
sonar.exclusions=**/__init__.py,**/data/**
# Coverage report path (if using coverage tools like coverage.py)
# sonar.python.coverage.reportPaths=coverage.xml
